version: "3"
services:
  planning-poker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - EXTERNAL_URL=https://planning-poker.placeloop.io
    ports:
      - 80:8000
    volumes:
      - planning-poker-data:/data
volumes:
  planning-poker-data: {}
